### ISSUE TITLE
A problem for Dice Loss

### ISSUE THREAD

**Issue by Thornhill-GYL** [ShannonAI/mrc-for-flat-nested-ner#59]
The address "https://github.com/ShannonAI/dice_loss_for_NLP" in your paper《Dice Loss for Data-imbalanced NLP Tasks》can't be find!  I would like to konw how can I get the code for dice_loss? Will you public it? Thanks.

**Comment by albertnanda** [comment]
Here is the code of dice loss: https://github.com/ShannonAI/mrc-for-flat-nested-ner/blob/master/loss/dice_loss.py

Though, I am not able to use this with huggingface token classification task. There is shape mismatch, because output from model is [batch_size, max_seq_len, num_labels] and labels are of the shape [batch_size, max_seq_len].

**Comment by Thornhill-GYL** [comment]
I have the same problem too.

**Comment by algoflow19** [comment]
They are working for binary classification only in fact.

**Comment by Jordy-VL** [comment]
Does anyone already have an extension to multi-class classification? 
Or is this only well-defined for binary classification?

**Comment by YuxianMeng** [comment]
Hi guys,  sorry for the late reply. For the dice loss, please use [our latest repo here.](https://github.com/ShannonAI/dice_loss_for_NLP)
